# Generated by Django 3.2 on 2021-06-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('start_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('mobno', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
    ]
