# Generated by Django 3.2 on 2021-06-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='eid',
            field=models.CharField(default=100, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='salary',
            field=models.IntegerField(default=15000),
        ),
    ]
