# Generated by Django 3.2 on 2021-06-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_crud', '0002_auto_20210618_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee_details',
            new_name='EmployeeDetails',
        ),
    ]
